###############################################################
# terraform/modules/networking/main.tf
# VNet, subnets, NSGs, Route Tables, Private DNS zones
# FCA: all NSG rules in Terraform — no portal modifications
###############################################################

resource "azurerm_virtual_network" "main" {
  name                = "vnet-${var.project}-${var.environment}-${var.location_short}"
    location            = var.location
      resource_group_name = var.resource_group_name
        address_space       = var.vnet_address_space
          tags                = var.tags
          }

          ###############################################################
          # Subnets
          ###############################################################

          resource "azurerm_subnet" "aks" {
            name                 = "snet-aks-${var.environment}"
              resource_group_name  = var.resource_group_name
                virtual_network_name = azurerm_virtual_network.main.name
                  address_prefixes     = [var.aks_subnet_address_prefix]

                    service_endpoints = [
                        "Microsoft.ContainerRegistry",
                            "Microsoft.KeyVault",
                                "Microsoft.Storage",
                                  ]
                                  }

                                  resource "azurerm_subnet" "appgateway" {
                                    name                 = "snet-agw-${var.environment}"
                                      resource_group_name  = var.resource_group_name
                                        virtual_network_name = azurerm_virtual_network.main.name
                                          address_prefixes     = [var.agw_subnet_address_prefix]
                                          }

                                          resource "azurerm_subnet" "private_endpoints" {
                                            name                 = "snet-pe-${var.environment}"
                                              resource_group_name  = var.resource_group_name
                                                virtual_network_name = azurerm_virtual_network.main.name
                                                  address_prefixes     = [var.pe_subnet_address_prefix]

                                                    private_endpoint_network_policies = "Disabled"
                                                    }

                                                    ###############################################################
                                                    # NSG — AKS subnet
                                                    # DenyAllInbound at priority 4096 is the baseline.
                                                    # All allow rules are explicit and version-controlled here.
                                                    # Lesson learned: portal-created rules caused API unreachability
                                                    # during NSG hardening. All rules must live in Terraform.
                                                    ###############################################################

                                                    resource "azurerm_network_security_group" "aks" {
                                                      name                = "nsg-aks-${var.project}-${var.environment}"
                                                        location            = var.location
                                                          resource_group_name = var.resource_group_name
                                                            tags                = var.tags

                                                              security_rule {
                                                                  name                       = "AllowAzureLoadBalancer"
                                                                      priority                   = 100
                                                                          direction                  = "Inbound"
                                                                              access                     = "Allow"
                                                                                  protocol                   = "Tcp"
                                                                                      source_port_range          = "*"
                                                                                          destination_port_range     = "*"
                                                                                              source_address_prefix      = "AzureLoadBalancer"
                                                                                                  destination_address_prefix = "*"
                                                                                                    }
                                                                                                    
                                                                                                      security_rule {
                                                                                                          name                       = "AllowAKSControlPlane"
                                                                                                              priority                   = 110
                                                                                                                  direction                  = "Inbound"
                                                                                                                      access                     = "Allow"
                                                                                                                          protocol                   = "Tcp"
                                                                                                                              source_port_range          = "*"
                                                                                                                                  destination_port_ranges    = ["443", "10250"]
                                                                                                                                      source_address_prefix      = "AzureCloud"
                                                                                                                                          destination_address_prefix = var.aks_subnet_address_prefix
                                                                                                                                            }
                                                                                                                                            
                                                                                                                                              security_rule {
                                                                                                                                                  name                       = "AllowVnetInbound"
                                                                                                                                                      priority                   = 200
                                                                                                                                                          direction                  = "Inbound"
                                                                                                                                                              access                     = "Allow"
                                                                                                                                                                  protocol                   = "*"
                                                                                                                                                                      source_port_range          = "*"
                                                                                                                                                                          destination_port_range     = "*"
                                                                                                                                                                              source_address_prefix      = "VirtualNetwork"
                                                                                                                                                                                  destination_address_prefix = "VirtualNetwork"
                                                                                                                                                                                    }
                                                                                                                                                                                    
                                                                                                                                                                                      security_rule {
                                                                                                                                                                                          name                       = "DenyAllInbound"
                                                                                                                                                                                              priority                   = 4096
                                                                                                                                                                                                  direction                  = "Inbound"
                                                                                                                                                                                                      access                     = "Deny"
                                                                                                                                                                                                          protocol                   = "*"
                                                                                                                                                                                                              source_port_range          = "*"
                                                                                                                                                                                                                  destination_port_range     = "*"
                                                                                                                                                                                                                      source_address_prefix      = "*"
                                                                                                                                                                                                                          destination_address_prefix = "*"
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            resource "azurerm_subnet_network_security_group_association" "aks" {
                                                                                                                                                                                                                              subnet_id                 = azurerm_subnet.aks.id
                                                                                                                                                                                                                                network_security_group_id = azurerm_network_security_group.aks.id
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                ###############################################################
                                                                                                                                                                                                                                # NSG — Application Gateway subnet
                                                                                                                                                                                                                                ###############################################################
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                resource "azurerm_network_security_group" "appgateway" {
                                                                                                                                                                                                                                  name                = "nsg-agw-${var.project}-${var.environment}"
                                                                                                                                                                                                                                    location            = var.location
                                                                                                                                                                                                                                      resource_group_name = var.resource_group_name
                                                                                                                                                                                                                                        tags                = var.tags
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          # Required by Azure Application Gateway v2
                                                                                                                                                                                                                                            security_rule {
                                                                                                                                                                                                                                                name                       = "AllowAGWManagement"
                                                                                                                                                                                                                                                    priority                   = 100
                                                                                                                                                                                                                                                        direction                  = "Inbound"
                                                                                                                                                                                                                                                            access                     = "Allow"
                                                                                                                                                                                                                                                                protocol                   = "Tcp"
                                                                                                                                                                                                                                                                    source_port_range          = "*"
                                                                                                                                                                                                                                                                        destination_port_range     = "65200-65535"
                                                                                                                                                                                                                                                                            source_address_prefix      = "GatewayManager"
                                                                                                                                                                                                                                                                                destination_address_prefix = "*"
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                    security_rule {
                                                                                                                                                                                                                                                                                        name                       = "AllowHTTPS"
                                                                                                                                                                                                                                                                                            priority                   = 110
                                                                                                                                                                                                                                                                                                direction                  = "Inbound"
                                                                                                                                                                                                                                                                                                    access                     = "Allow"
                                                                                                                                                                                                                                                                                                        protocol                   = "Tcp"
                                                                                                                                                                                                                                                                                                            source_port_range          = "*"
                                                                                                                                                                                                                                                                                                                destination_port_range     = "443"
                                                                                                                                                                                                                                                                                                                    source_address_prefix      = "*"
                                                                                                                                                                                                                                                                                                                        destination_address_prefix = "*"
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                            security_rule {
                                                                                                                                                                                                                                                                                                                                name                       = "DenyAllInbound"
                                                                                                                                                                                                                                                                                                                                    priority                   = 4096
                                                                                                                                                                                                                                                                                                                                        direction                  = "Inbound"
                                                                                                                                                                                                                                                                                                                                            access                     = "Deny"
                                                                                                                                                                                                                                                                                                                                                protocol                   = "*"
                                                                                                                                                                                                                                                                                                                                                    source_port_range          = "*"
                                                                                                                                                                                                                                                                                                                                                        destination_port_range     = "*"
                                                                                                                                                                                                                                                                                                                                                            source_address_prefix      = "*"
                                                                                                                                                                                                                                                                                                                                                                destination_address_prefix = "*"
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                  resource "azurerm_subnet_network_security_group_association" "appgateway" {
                                                                                                                                                                                                                                                                                                                                                                    subnet_id                 = azurerm_subnet.appgateway.id
                                                                                                                                                                                                                                                                                                                                                                      network_security_group_id = azurerm_network_security_group.appgateway.id
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                      ###############################################################
                                                                                                                                                                                                                                                                                                                                                                      # Route Table — force all AKS egress through Azure Firewall
                                                                                                                                                                                                                                                                                                                                                                      ###############################################################
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                      resource "azurerm_route_table" "aks" {
                                                                                                                                                                                                                                                                                                                                                                        name                          = "rt-aks-${var.project}-${var.environment}"
                                                                                                                                                                                                                                                                                                                                                                          location                      = var.location
                                                                                                                                                                                                                                                                                                                                                                            resource_group_name           = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                              bgp_route_propagation_enabled = false
                                                                                                                                                                                                                                                                                                                                                                                tags                          = var.tags
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                  route {
                                                                                                                                                                                                                                                                                                                                                                                      name                   = "DefaultRouteToFirewall"
                                                                                                                                                                                                                                                                                                                                                                                          address_prefix         = "0.0.0.0/0"
                                                                                                                                                                                                                                                                                                                                                                                              next_hop_type          = "VirtualAppliance"
                                                                                                                                                                                                                                                                                                                                                                                                  next_hop_in_ip_address = var.firewall_private_ip
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                    resource "azurerm_subnet_route_table_association" "aks" {
                                                                                                                                                                                                                                                                                                                                                                                                      subnet_id      = azurerm_subnet.aks.id
                                                                                                                                                                                                                                                                                                                                                                                                        route_table_id = azurerm_route_table.aks.id
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                        ###############################################################
                                                                                                                                                                                                                                                                                                                                                                                                        # Private DNS Zones — required for private endpoint resolution
                                                                                                                                                                                                                                                                                                                                                                                                        ###############################################################
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                        resource "azurerm_private_dns_zone" "keyvault" {
                                                                                                                                                                                                                                                                                                                                                                                                          name                = "privatelink.vaultcore.azure.net"
                                                                                                                                                                                                                                                                                                                                                                                                            resource_group_name = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                              tags                = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                              resource "azurerm_private_dns_zone_virtual_network_link" "keyvault" {
                                                                                                                                                                                                                                                                                                                                                                                                                name                  = "pdnslink-kv-${var.environment}"
                                                                                                                                                                                                                                                                                                                                                                                                                  resource_group_name   = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                                    private_dns_zone_name = azurerm_private_dns_zone.keyvault.name
                                                                                                                                                                                                                                                                                                                                                                                                                      virtual_network_id    = azurerm_virtual_network.main.id
                                                                                                                                                                                                                                                                                                                                                                                                                        registration_enabled  = false
                                                                                                                                                                                                                                                                                                                                                                                                                          tags                  = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          resource "azurerm_private_dns_zone" "acr" {
                                                                                                                                                                                                                                                                                                                                                                                                                            name                = "privatelink.azurecr.io"
                                                                                                                                                                                                                                                                                                                                                                                                                              resource_group_name = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                                                tags                = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                resource "azurerm_private_dns_zone_virtual_network_link" "acr" {
                                                                                                                                                                                                                                                                                                                                                                                                                                  name                  = "pdnslink-acr-${var.environment}"
                                                                                                                                                                                                                                                                                                                                                                                                                                    resource_group_name   = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                                                      private_dns_zone_name = azurerm_private_dns_zone.acr.name
                                                                                                                                                                                                                                                                                                                                                                                                                                        virtual_network_id    = azurerm_virtual_network.main.id
                                                                                                                                                                                                                                                                                                                                                                                                                                          registration_enabled  = false
                                                                                                                                                                                                                                                                                                                                                                                                                                            tags                  = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                            resource "azurerm_private_dns_zone" "servicebus" {
                                                                                                                                                                                                                                                                                                                                                                                                                                              name                = "privatelink.servicebus.windows.net"
                                                                                                                                                                                                                                                                                                                                                                                                                                                resource_group_name = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                                                                  tags                = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                  resource "azurerm_private_dns_zone_virtual_network_link" "servicebus" {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    name                  = "pdnslink-sb-${var.environment}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      resource_group_name   = var.resource_group_name
                                                                                                                                                                                                                                                                                                                                                                                                                                                        private_dns_zone_name = azurerm_private_dns_zone.servicebus.name
                                                                                                                                                                                                                                                                                                                                                                                                                                                          virtual_network_id    = azurerm_virtual_network.main.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                            registration_enabled  = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                              tags                  = var.tags
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
